name = "senquara-one"
main = "worker/index.js"
compatibility_date = "2026-09-15"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "senquara-one-db"
database_id = "5caf94de-b69f-402c-881d-2f7e564a3084"

# Set APP_SECRET as a Cloudflare Worker Secret for production.

