// SENQUARA ONE — authenticated D1 Worker
// Roles: master_admin, admin, staff
const JSON_HEADERS={"content-type":"application/json;charset=UTF-8","cache-control":"no-store"};
const ROLES={
  master_admin:{name:"Master Admin",permissions:["view","create","edit","delete","approve","export","manage_users","manage_roles","block_users","settings","backup"]},
  admin:{name:"Admin",permissions:["view","create","edit","delete","export"]},
  staff:{name:"Staff",permissions:["view","create","edit"]}
};
const id=()=>crypto.randomUUID();
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:JSON_HEADERS});
function cors(r){r.headers.set("Access-Control-Allow-Origin","*");r.headers.set("Access-Control-Allow-Headers","Content-Type, Authorization");r.headers.set("Access-Control-Allow-Methods","GET,POST,PUT,DELETE,OPTIONS");return r}
function b64u(data){return btoa(String.fromCharCode(...new Uint8Array(data))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function ub64(s){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function hashPassword(password,saltValue){const salt=saltValue?ub64(saltValue):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:100000,hash:"SHA-256"},key,256);return{salt:b64u(salt),hash:b64u(bits)}}
async function sign(payload,secret){if(!secret)throw new Error("APP_SECRET is not configured");const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const body=b64u(new TextEncoder().encode(JSON.stringify(payload)));const sig=b64u(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(body)));return `${body}.${sig}`}
async function verifyToken(token,secret){try{if(!token||!secret)return null;const p=token.split(".");if(p.length!==2)return null;const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",key,ub64(p[1]),new TextEncoder().encode(p[0])))return null;const payload=JSON.parse(new TextDecoder().decode(ub64(p[0])));return payload.exp>Date.now()?payload:null}catch{return null}}
function userView(u){return{id:u.id,name:u.name,email:u.email,mobile:u.mobile||"",businessName:u.business_name||"",country:u.country||"",role:normalizeRole(u.role),status:u.status||"active",blocked:Number(u.blocked||0)===1,mustChangePassword:Number(u.must_change_password||0)===1,googleLinked:!!u.google_sub}}
function normalizeRole(role){if(role==="owner")return"master_admin";if(["manager","accountant"].includes(role))return"admin";if(["billing","inventory","sales","viewer"].includes(role))return"staff";return ROLES[role]?role:"staff"}
async function audit(env,user,action,entity,entityId,details={}){try{await env.DB.prepare("INSERT INTO audit_log(id,user_id,action,entity,entity_id,details,created_at) VALUES(?,?,?,?,?,?,datetime('now'))").bind(id(),user?.id||null,action,entity,entityId,JSON.stringify(details)).run()}catch{}}
async function getUser(request,env){const h=request.headers.get("Authorization")||"";const t=h.startsWith("Bearer ")?h.slice(7):"";const p=await verifyToken(t,env.APP_SECRET);if(!p)return null;const u=await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(p.sub).first();if(!u)return null;if(Number(u.blocked||0)===1||u.status==="blocked")return null;return u}
async function requireUser(request,env){const user=await getUser(request,env);return user?{user}: {error:json({error:"Authentication required"},401)}}
function requirePermission(user,permission){const role=normalizeRole(user.role);return ROLES[role]?.permissions.includes(permission)}
async function ensureColumns(env){
try{await env.DB.prepare("ALTER TABLE users ADD COLUMN status TEXT NOT NULL DEFAULT 'active'").run()}catch{}
try{await env.DB.prepare("ALTER TABLE users ADD COLUMN updated_at TEXT").run()}catch{}
try{await env.DB.prepare("ALTER TABLE users ADD COLUMN blocked INTEGER NOT NULL DEFAULT 0").run()}catch{}
try{await env.DB.prepare("ALTER TABLE users ADD COLUMN blocked_at TEXT").run()}catch{}
try{await env.DB.prepare("ALTER TABLE users ADD COLUMN must_change_password INTEGER NOT NULL DEFAULT 0").run()}catch{}
try{await env.DB.prepare("ALTER TABLE users ADD COLUMN google_sub TEXT").run()}catch{}
try{await env.DB.prepare("ALTER TABLE users ADD COLUMN google_email TEXT").run()}catch{}
}
async function ensurePresenceTables(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_presence(user_id TEXT PRIMARY KEY,ip TEXT,country TEXT,region TEXT,city TEXT,latitude REAL,longitude REAL,timezone TEXT,colo TEXT,user_agent TEXT,presence_status TEXT NOT NULL DEFAULT 'online',last_error TEXT,last_seen TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`).run();try{await env.DB.prepare("ALTER TABLE user_presence ADD COLUMN user_agent TEXT").run()}catch{}await env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_user_presence_last_seen ON user_presence(last_seen)").run()}
function requestGeo(request){const cf=request.cf||{};return{ip:request.headers.get("CF-Connecting-IP")||"",country:cf.country||request.headers.get("CF-IPCountry")||"",region:cf.region||"",city:cf.city||"",latitude:cf.latitude==null?null:Number(cf.latitude),longitude:cf.longitude==null?null:Number(cf.longitude),timezone:cf.timezone||"",colo:cf.colo||"",userAgent:request.headers.get("User-Agent")||""}}
async function presenceHeartbeat(request,env,user){await ensurePresenceTables(env);const body=await request.json().catch(()=>({})),g=requestGeo(request),status=["online","problem"].includes(body.status)?body.status:"online",err=String(body.error||"").slice(0,250),now=new Date().toISOString();await env.DB.prepare(`INSERT INTO user_presence(user_id,ip,country,region,city,latitude,longitude,timezone,colo,user_agent,presence_status,last_error,last_seen,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET ip=excluded.ip,country=excluded.country,region=excluded.region,city=excluded.city,latitude=excluded.latitude,longitude=excluded.longitude,timezone=excluded.timezone,colo=excluded.colo,user_agent=excluded.user_agent,presence_status=excluded.presence_status,last_error=excluded.last_error,last_seen=excluded.last_seen,updated_at=excluded.updated_at`).bind(user.id,g.ip,g.country,g.region,g.city,g.latitude,g.longitude,g.timezone,g.colo,g.userAgent,status,err,now,now).run();return json({ok:true,last_seen:now})}
async function presenceList(env){await ensurePresenceTables(env);const rows=await env.DB.prepare(`SELECT u.id,u.email,u.name,u.mobile,u.country AS user_country,u.role,u.created_at,u.status,u.blocked,u.blocked_at,p.ip,p.country,p.region,p.city,p.latitude,p.longitude,p.timezone,p.colo,p.user_agent,p.presence_status,p.last_error,p.last_seen,p.updated_at FROM users u LEFT JOIN user_presence p ON p.user_id=u.id ORDER BY u.created_at DESC`).all();const six=Date.now()-183*86400000,active=Date.now()-90000;const users=(rows.results||[]).map(r=>{const status=Number(r.blocked)?"offline":r.presence_status==="problem"||r.last_error?"problem":r.last_seen&&new Date(r.last_seen).getTime()>=active?"online":r.last_seen&&new Date(r.last_seen).getTime()<six||(!r.last_seen&&new Date(r.created_at).getTime()<six)?"pink":"offline";return{...r,role:normalizeRole(r.role),country:r.country||r.user_country||"",statusPresence:status}});return{users,online_count:users.filter(x=>x.statusPresence==="online").length,new_users:users.filter(x=>Date.now()-new Date(x.created_at).getTime()<15*60*1000).length}}
async function readRecord(env,userId,type,fallback=[]){const r=await env.DB.prepare("SELECT id,data,version,updated_at FROM business_records WHERE user_id=? AND record_type=?").bind(userId,type).first();if(!r)return{data:fallback,version:0,updatedAt:null,id:null};try{return{data:JSON.parse(r.data),version:r.version,updatedAt:r.updated_at,id:r.id}}catch{return{data:fallback,version:r.version,updatedAt:r.updated_at,id:r.id}}}
async function writeRecord(env,user,type,data){const now=new Date().toISOString();const old=await env.DB.prepare("SELECT id,version FROM business_records WHERE user_id=? AND record_type=?").bind(user.id,type).first();const next=(old?.version||0)+1,rid=old?.id||id();await env.DB.prepare(`INSERT INTO business_records(id,user_id,record_type,data,version,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id,record_type) DO UPDATE SET data=excluded.data,version=excluded.version,updated_at=excluded.updated_at`).bind(rid,user.id,type,JSON.stringify(data),next,now).run();await audit(env,user,"save","business_records",rid,{type,version:next});return{data,version:next,updatedAt:now,id:rid}}
function cleanType(s){return String(s||"").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,60)}
async function bootstrapFirstAdmin(env,email,password){
  const c=await env.DB.prepare("SELECT COUNT(*) AS total FROM users").first();
  if(Number(c?.total||0)!==0) return null;
  if(email!=="admin@senquara.one" || password!=="admin") return false;
  const pw=await hashPassword(password),uid=id(),now=new Date().toISOString();
  await env.DB.prepare("INSERT INTO users(id,email,name,mobile,business_name,country,password_hash,password_salt,role,status,email_verified,terms_version,terms_accepted_at,created_at,updated_at,must_change_password) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1)").bind(uid,email,"Master Admin","","SENQUARA ONE","India",pw.hash,pw.salt,"master_admin","active",1,"1.0",now,now,now).run();
  await env.DB.prepare("INSERT OR IGNORE INTO user_roles(id,user_id,role_id) VALUES(?,?,?)").bind(id(),uid,"master_admin").run();
  await audit(env,null,"bootstrap_master_admin","users",uid,{});
  return await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(uid).first();
}
async function register(request,env){await ensureColumns(env);const b=await request.json();const name=String(b.name||"").trim(),businessName=String(b.businessName||"").trim(),email=String(b.email||"").trim().toLowerCase(),mobile=String(b.mobile||"").trim(),country=String(b.country||"").trim(),password=String(b.password||"");if(!name||!email||!mobile||!password)return json({error:"Full name, email, mobile and password are required"},400);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({error:"Please enter a valid email address"},400);if(password.length<8)return json({error:"Password must contain at least 8 characters"},400);if(b.termsAccepted!==true)return json({error:"Please accept the Terms and Conditions"},400);if(await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first())return json({error:"Email already registered"},409);const c=await env.DB.prepare("SELECT COUNT(*) AS total FROM users").first(),first=Number(c?.total||0)===0,pw=await hashPassword(password),uid=id(),now=new Date().toISOString(),role=first?"master_admin":"staff",status=first?"active":"pending";await env.DB.prepare("INSERT INTO users(id,email,name,mobile,business_name,country,password_hash,password_salt,role,status,email_verified,terms_version,terms_accepted_at,created_at,updated_at,must_change_password) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0)").bind(uid,email,name,mobile,businessName,country,pw.hash,pw.salt,role,status,1,String(b.termsVersion||"1.0"),now,now,now).run();await env.DB.prepare("INSERT OR IGNORE INTO user_roles(id,user_id,role_id) VALUES(?,?,?)").bind(id(),uid,role).run();await audit(env,null,"register","users",uid,{email,role});if(!first)return json({pending:true,user:{id:uid,name,businessName,email,mobile,country,role,status},message:"Registration received. Your account is pending Master Admin approval."});const token=await sign({sub:uid,exp:Date.now()+7*86400000},env.APP_SECRET);return json({token,user:userView({id:uid,name,business_name:businessName,email,mobile,country,role,status,must_change_password:0}),message:"Master Admin account created."})}
async function login(request,env){await ensureColumns(env);const b=await request.json(),email=String(b.email||"").trim().toLowerCase(),password=String(b.password||""),requestedRole=normalizeRole(String(b.role||"staff"));if(!email||!password)return json({error:"Email, password and role are required"},400);let u=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(email).first();if(!u){const boot=await bootstrapFirstAdmin(env,email,password);if(boot&&boot!==false)u=boot;else if(boot===false)return json({error:"First login is reserved for Master Admin. Use admin@senquara.one / admin, then change the password."},401);else return json({error:"Invalid email or password"},401)}if(Number(u.blocked||0)||u.status==="blocked")return json({error:"This account is blocked. Contact Master Admin."},403);if(u.status==="pending")return json({pending:true,error:"Your account is pending Master Admin approval."},403);if(normalizeRole(u.role)!==requestedRole)return json({error:"Selected role does not match this account."},403);const pw=await hashPassword(password,u.password_salt);if(pw.hash!==u.password_hash)return json({error:"Invalid email or password"},401);const token=await sign({sub:u.id,exp:Date.now()+7*86400000},env.APP_SECRET);await audit(env,u,"login","users",u.id,{role:requestedRole});return json({token,user:userView(u)})}
async function changePassword(request,env,actor){const b=await request.json(),current=String(b.currentPassword||""),next=String(b.newPassword||"");if(next.length<8)return json({error:"New password must contain at least 8 characters"},400);const old=await hashPassword(current,actor.password_salt);if(old.hash!==actor.password_hash)return json({error:"Current password is incorrect"},400);const pw=await hashPassword(next),now=new Date().toISOString();await env.DB.prepare("UPDATE users SET password_hash=?,password_salt=?,must_change_password=0,updated_at=? WHERE id=?").bind(pw.hash,pw.salt,now,actor.id).run();await audit(env,actor,"change_password","users",actor.id,{});return json({ok:true})}
async function linkGoogle(request,env,actor){if(!env.GOOGLE_CLIENT_ID)return json({error:"Google linking is not configured. Add GOOGLE_CLIENT_ID to the Worker environment."},503);const b=await request.json(),credential=String(b.credential||"");if(!credential)return json({error:"Google credential is required"},400);const r=await fetch("https://oauth2.googleapis.com/tokeninfo?id_token="+encodeURIComponent(credential));if(!r.ok)return json({error:"Google credential could not be verified"},401);const g=await r.json();if(g.aud!==env.GOOGLE_CLIENT_ID)return json({error:"Google client mismatch"},401);const now=new Date().toISOString();await env.DB.prepare("UPDATE users SET google_sub=?,google_email=?,updated_at=? WHERE id=?").bind(String(g.sub||""),String(g.email||""),now,actor.id).run();await audit(env,actor,"link_google","users",actor.id,{google_email:g.email||""});return json({ok:true,email:g.email||""})}
async function listUsers(env){const rows=await env.DB.prepare("SELECT id,email,name,mobile,business_name,country,role,status,blocked,created_at,updated_at FROM users ORDER BY created_at DESC").all();return(rows.results||[]).map(u=>({...u,role:normalizeRole(u.role),blocked:Number(u.blocked||0)===1}))}
async function upsertUser(request,env,actor){if(!requirePermission(actor,"manage_users"))return json({error:"Master Admin access required"},403);const b=await request.json(),uid=String(b.userId||b.id||"").trim(),name=String(b.name||"").trim(),email=String(b.email||"").trim().toLowerCase(),role=normalizeRole(b.role),status=["pending","active","blocked"].includes(b.status)?b.status:"active";if(!name||!email)return json({error:"Name and email are required"},400);if(!ROLES[role])return json({error:"Invalid role"},400);if(role==="master_admin" && normalizeRole(actor.role)!=="master_admin")return json({error:"Only Master Admin may create another Master Admin"},403);if(uid){if(uid===actor.id&&role!=="master_admin")return json({error:"You cannot remove your own Master Admin role"},400);await env.DB.prepare("UPDATE users SET name=?,email=?,mobile=?,business_name=?,country=?,role=?,status=?,blocked=?,blocked_at=?,updated_at=? WHERE id=?").bind(name,email,String(b.mobile||""),String(b.businessName||""),String(b.country||""),role,status,status==="blocked"?1:0,status==="blocked"?new Date().toISOString():null,new Date().toISOString(),uid).run();await audit(env,actor,"update_user","users",uid,{role,status});return json({ok:true,userId:uid})}const password=String(b.password||"");if(password.length<8)return json({error:"New user password must contain at least 8 characters"},400);const pw=await hashPassword(password),nid=id(),now=new Date().toISOString();await env.DB.prepare("INSERT INTO users(id,email,name,mobile,business_name,country,password_hash,password_salt,role,status,email_verified,terms_version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(nid,email,name,String(b.mobile||""),String(b.businessName||""),String(b.country||""),pw.hash,pw.salt,role,status,1,"1.0",now,now).run();await env.DB.prepare("INSERT OR IGNORE INTO user_roles(id,user_id,role_id) VALUES(?,?,?)").bind(id(),nid,role).run();await audit(env,actor,"create_user","users",nid,{role});return json({ok:true,userId:nid})}
async function setUserStatus(request,env,actor){if(!requirePermission(actor,"manage_users"))return json({error:"Master Admin access required"},403);const b=await request.json(),uid=String(b.userId||b.id||""),status=String(b.status||"");if(!uid||!["pending","active","blocked"].includes(status))return json({error:"Valid userId and status are required"},400);if(uid===actor.id&&status!=="active")return json({error:"You cannot disable your own Master Admin account"},400);await env.DB.prepare("UPDATE users SET status=?,blocked=?,blocked_at=?,updated_at=? WHERE id=?").bind(status,status==="blocked"?1:0,status==="blocked"?new Date().toISOString():null,new Date().toISOString(),uid).run();await audit(env,actor,"user_status","users",uid,{status});return json({ok:true})}
async function setUserRole(request,env,actor){if(!requirePermission(actor,"manage_roles"))return json({error:"Master Admin access required"},403);const b=await request.json(),uid=String(b.userId||""),role=String(b.role||"");if(!uid||!ROLES[role])return json({error:"Valid userId and role are required"},400);if(uid===actor.id&&role!=="master_admin")return json({error:"You cannot remove your own Master Admin role"},400);await env.DB.prepare("UPDATE users SET role=?,updated_at=? WHERE id=?").bind(role,new Date().toISOString(),uid).run();await env.DB.prepare("INSERT OR IGNORE INTO user_roles(id,user_id,role_id) VALUES(?,?,?)").bind(id(),uid,role).run();await audit(env,actor,"role_change","users",uid,{role});return json({ok:true})}
async function blockUser(request,env,actor){if(!requirePermission(actor,"block_users"))return json({error:"Master Admin access required"},403);const b=await request.json(),uid=String(b.userId||""),blocked=!!b.blocked;if(!uid)return json({error:"userId is required"},400);if(uid===actor.id)return json({error:"You cannot block your own account"},400);await env.DB.prepare("UPDATE users SET blocked=?,blocked_at=?,status=?,updated_at=? WHERE id=?").bind(blocked?1:0,blocked?new Date().toISOString():null,blocked?"blocked":"active",new Date().toISOString(),uid).run();await audit(env,actor,blocked?"block_user":"unblock_user","users",uid,{blocked});return json({ok:true,blocked})}
async function readAudit(env,actor){if(!requirePermission(actor,"manage_users"))return json({error:"Master Admin access required"},403);const rows=await env.DB.prepare("SELECT * FROM audit_log ORDER BY created_at DESC LIMIT 200").all();return json({logs:rows.results||[]})}
async function handle(request,env){if(request.method==="OPTIONS")return new Response(null,{status:204});const url=new URL(request.url);if(url.pathname==="/api/health"&&request.method==="GET")return json({ok:true,service:"SENQUARA ONE",roles:Object.keys(ROLES)});if(url.pathname==="/api/auth/register"&&request.method==="POST")return register(request,env);if(url.pathname==="/api/auth/login"&&request.method==="POST")return login(request,env);const auth=await requireUser(request,env);if(auth.error)return auth.error;const user=auth.user;
if(url.pathname==="/api/auth/me"&&request.method==="GET")return json({user:userView(user)});
if(url.pathname==="/api/auth/logout"&&request.method==="POST")return json({ok:true});
if(url.pathname==="/api/auth/change-password"&&request.method==="POST")return changePassword(request,env,user);
if(url.pathname==="/api/auth/link-google"&&request.method==="POST")return linkGoogle(request,env,user);
if(url.pathname==="/api/presence/heartbeat"&&request.method==="POST")return presenceHeartbeat(request,env,user);
if(url.pathname==="/api/presence"&&request.method==="GET"){if(!requirePermission(user,"manage_users"))return json({error:"Master Admin access required"},403);return json(await presenceList(env))}
if(url.pathname==="/api/presence/summary"&&request.method==="GET"){if(!requirePermission(user,"manage_users"))return json({error:"Master Admin access required"},403);const p=await presenceList(env);return json({online_count:p.online_count,new_users:p.new_users,total_users:p.users.length})}
if(url.pathname==="/api/users"&&request.method==="GET"){if(!requirePermission(user,"manage_users"))return json({error:"Master Admin access required"},403);return json({users:await listUsers(env)})}
if(url.pathname==="/api/users"&&request.method==="POST")return upsertUser(request,env,user);
if(url.pathname==="/api/users/status"&&request.method==="PUT")return setUserStatus(request,env,user);
if(url.pathname==="/api/users/role"&&request.method==="PUT")return setUserRole(request,env,user);
if(url.pathname==="/api/users/block"&&request.method==="PUT")return blockUser(request,env,user);
if(url.pathname==="/api/audit"&&request.method==="GET")return readAudit(env,user);
if(url.pathname==="/api/data"&&request.method==="GET"){if(!requirePermission(user,"view"))return json({error:"Access denied"},403);const type=cleanType(url.searchParams.get("type"));if(!type)return json({error:"type is required"},400);return json(await readRecord(env,user.id,type,[]))}
if(url.pathname==="/api/data"&&request.method==="PUT"){if(!requirePermission(user,"edit"))return json({error:"Edit access required"},403);const b=await request.json(),type=cleanType(b.type);if(!type)return json({error:"type is required"},400);return json(await writeRecord(env,user,type,b.data??{}))}
if(url.pathname==="/api/dashboard"&&request.method==="GET"){const types=["invoices","products","people","payments","expenses","quotes","orders","receipts","returns"],out={};for(const t of types)out[t]=(await readRecord(env,user.id,t,[])).data;return json(out)}
if(url.pathname==="/api/master"&&request.method==="GET")return json(await readRecord(env,user.id,"master",{}));
if(url.pathname==="/api/master"&&request.method==="PUT"){if(!requirePermission(user,"settings"))return json({error:"Master Admin access required"},403);return json(await writeRecord(env,user,"master",(await request.json()).data||{}))}
if(url.pathname==="/api/profile"&&request.method==="PUT"){if(!requirePermission(user,"edit"))return json({error:"Edit access required"},403);const b=await request.json();await env.DB.prepare("UPDATE users SET name=?,mobile=?,business_name=?,country=?,updated_at=? WHERE id=?").bind(b.name||user.name,b.mobile||"",b.businessName||user.business_name,b.country||user.country,new Date().toISOString(),user.id).run();await audit(env,user,"update_profile","users",user.id,{});return json({user:userView({...user,...b,business_name:b.businessName||user.business_name})})}
return json({error:"Not found"},404)}
export default{async fetch(request,env){try{return cors(await handle(request,env))}catch(e){return cors(json({error:"Server error",detail:String(e?.message||e)},500))}}};
