const JSON_HEADERS={"content-type":"application/json;charset=UTF-8","cache-control":"no-store"};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:JSON_HEADERS});
function cors(r){r.headers.set("Access-Control-Allow-Origin","*");r.headers.set("Access-Control-Allow-Headers","Content-Type, Authorization");r.headers.set("Access-Control-Allow-Methods","GET,POST,PUT,DELETE,OPTIONS");return r}
function b64u(data){return btoa(String.fromCharCode(...new Uint8Array(data))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function ub64(s){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function hashPassword(password,saltValue){const salt=saltValue?ub64(saltValue):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:100000,hash:"SHA-256"},key,256);return{salt:b64u(salt),hash:b64u(bits)}}
async function sign(payload,secret){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const body=b64u(new TextEncoder().encode(JSON.stringify(payload)));const sig=b64u(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(body)));return `${body}.${sig}`}
async function verifyToken(token,secret){try{if(!token||!secret)return null;const p=token.split(".");if(p.length!==2)return null;const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",key,ub64(p[1]),new TextEncoder().encode(p[0])))return null;const payload=JSON.parse(new TextDecoder().decode(ub64(p[0])));return payload.exp>Date.now()?payload:null}catch{return null}}
const id=()=>crypto.randomUUID();
async function getUser(request,env){const h=request.headers.get("Authorization")||"";const t=h.startsWith("Bearer ")?h.slice(7):"";const p=await verifyToken(t,env.APP_SECRET);if(!p)return null;return await env.DB.prepare("SELECT id,email,name,mobile,business_name,country,role FROM users WHERE id=?").bind(p.sub).first()}
async function audit(env,user,action,entity,entityId,details={}){try{await env.DB.prepare("INSERT INTO audit_log(id,user_id,action,entity,entity_id,details,created_at) VALUES(?,?,?,?,?,?,datetime('now'))").bind(id(),user?.id||null,action,entity,entityId,JSON.stringify(details)).run()}catch{}}
function cleanType(s){return String(s||"").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,60)}
async function readRecord(env,userId,type, fallback=[]){const r=await env.DB.prepare("SELECT id,data,version,updated_at FROM business_records WHERE user_id=? AND record_type=?").bind(userId,type).first();if(!r)return{data:fallback,version:0,updatedAt:null,id:null};try{return{data:JSON.parse(r.data),version:r.version,updatedAt:r.updated_at,id:r.id}}catch{return{data:fallback,version:r.version,updatedAt:r.updated_at,id:r.id}}}
async function writeRecord(env,user,type,data){const now=new Date().toISOString();const old=await env.DB.prepare("SELECT id,version FROM business_records WHERE user_id=? AND record_type=?").bind(user.id,type).first();const next=(old?.version||0)+1;const rid=old?.id||id();await env.DB.prepare(`INSERT INTO business_records(id,user_id,record_type,data,version,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id,record_type) DO UPDATE SET data=excluded.data,version=excluded.version,updated_at=excluded.updated_at`).bind(rid,user.id,type,JSON.stringify(data),next,now).run();await audit(env,user,"save","business_records",rid,{type,version:next});return{data,version:next,updatedAt:now,id:rid}}
function defaultMaster(){return{taxProfiles:[{id:"gst5",name:"GST 5%",rate:5},{id:"gst12",name:"GST 12%",rate:12},{id:"gst18",name:"GST 18%",rate:18},{id:"gst28",name:"GST 28%",rate:28}],paymentMethods:[{id:"cash",name:"Cash",status:"active"},{id:"upi",name:"UPI",status:"active"},{id:"bank",name:"Bank Transfer",status:"active"},{id:"card",name:"Card",status:"active"},{id:"credit",name:"Credit",status:"active"}],roles:[{id:"owner",name:"Owner/Admin",permissions:["view","create","edit","delete","approve","export"]},{id:"manager",name:"Manager",permissions:["view","create","edit","approve","export"]},{id:"accountant",name:"Accountant",permissions:["view","create","edit","export"]},{id:"billing",name:"Billing Operator",permissions:["view","create"]},{id:"inventory",name:"Inventory Manager",permissions:["view","create","edit"]},{id:"sales",name:"Salesperson",permissions:["view","create"]},{id:"viewer",name:"Viewer",permissions:["view"]}],terms:[{id:"general",name:"General Terms",text:"Goods once sold are subject to applicable business terms."},{id:"payment",name:"Payment Terms",text:"Payment is due as agreed on the invoice."}],customData:[]}}
async function handle(request,env){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204});
if(url.pathname==="/api/health"&&request.method==="GET")return json({ok:true,service:"SENQUARA ONE Cloudflare D1 API",time:new Date().toISOString()});
if(url.pathname==="/api/auth/register"&&request.method==="POST"){const body=await request.json();if(!body.email||!body.password||!body.name||!body.businessName)return json({error:"Required registration fields are missing"},400);const email=String(body.email).trim().toLowerCase();if(await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first())return json({error:"Email already registered"},409);const pw=await hashPassword(String(body.password));const uid=id();await env.DB.prepare("INSERT INTO users(id,email,name,mobile,business_name,country,password_hash,password_salt,role,created_at) VALUES(?,?,?,?,?,?,?,?,?,datetime('now'))").bind(uid,email,String(body.name).trim(),body.mobile||"",String(body.businessName).trim(),body.country||"",pw.hash,pw.salt,"owner").run();await env.DB.prepare("INSERT OR IGNORE INTO user_roles(id,user_id,role_id) VALUES(?,?,?)").bind(id(),uid,"owner").run();const token=await sign({sub:uid,exp:Date.now()+7*24*60*60*1000},env.APP_SECRET);return json({token,user:{id:uid,name:body.name,email,mobile:body.mobile||"",business:{name:body.businessName,country:body.country||""},role:"owner"}})}
if(url.pathname==="/api/auth/login"&&request.method==="POST"){const body=await request.json();const email=String(body.email||"").trim().toLowerCase();const user=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(email).first();if(!user)return json({error:"Invalid email or password"},401);const pw=await hashPassword(String(body.password||""),user.password_salt);if(pw.hash!==user.password_hash)return json({error:"Invalid email or password"},401);const token=await sign({sub:user.id,exp:Date.now()+7*24*60*60*1000},env.APP_SECRET);return json({token,user:{id:user.id,name:user.name,email:user.email,mobile:user.mobile,business:{name:user.business_name,country:user.country},role:user.role}})}
const user=await getUser(request,env);if(!user)return json({error:"Authentication required"},401);
if(url.pathname==="/api/auth/me"&&request.method==="GET")return json({user:{id:user.id,name:user.name,email:user.email,mobile:user.mobile,business:{name:user.business_name,country:user.country},role:user.role}});
if(url.pathname==="/api/data"&&request.method==="GET"){const type=cleanType(url.searchParams.get("type"));if(!type)return json({error:"type is required"},400);return json(await readRecord(env,user.id,type,[]))}
if(url.pathname==="/api/data"&&request.method==="PUT"){const body=await request.json();const type=cleanType(body.type);if(!type)return json({error:"type is required"},400);return json(await writeRecord(env,user,type,body.data??{}))}
if(url.pathname==="/api/dashboard"&&request.method==="GET"){const types=["invoices","products","people","payments","expenses","quotes","orders","receipts","returns"];const out={};for(const t of types)out[t]=(await readRecord(env,user.id,t,[])).data;return json(out)}
if(url.pathname==="/api/master"&&request.method==="GET"){const r=await readRecord(env,user.id,"master",defaultMaster());return json(r)}
if(url.pathname==="/api/master"&&request.method==="PUT"){if(user.role!=="owner")return json({error:"Owner/Admin approval required"},403);const body=await request.json();return json(await writeRecord(env,user,"master",body.data||defaultMaster()))}
if(url.pathname==="/api/profile"&&request.method==="PUT"){const body=await request.json();await env.DB.prepare("UPDATE users SET name=?,mobile=?,business_name=?,country=? WHERE id=?").bind(body.name||user.name,body.mobile||"",body.businessName||user.business_name,body.country||user.country,user.id).run();await audit(env,user,"update","profile",user.id,{});return json({user:{...user,name:body.name||user.name,mobile:body.mobile||"",business_name:body.businessName||user.business_name,country:body.country||user.country}})}
if(url.pathname==="/api/users"&&request.method==="GET"){const rows=await env.DB.prepare("SELECT id,email,name,mobile,business_name,country,role,created_at FROM users ORDER BY created_at DESC").all();return json({users:rows.results||[]})}
if(url.pathname==="/api/users/role"&&request.method==="PUT"){if(user.role!=="owner")return json({error:"Owner/Admin only"},403);const body=await request.json();if(!body.userId||!body.role)return json({error:"userId and role required"},400);await env.DB.prepare("UPDATE users SET role=? WHERE id=?").bind(body.role,body.userId).run();await env.DB.prepare("INSERT OR IGNORE INTO user_roles(id,user_id,role_id) VALUES(?,?,?)").bind(id(),body.userId,body.role).run();await audit(env,user,"role_change","users",body.userId,{role:body.role});return json({ok:true})}
if(url.pathname==="/api/audit"&&request.method==="GET"){const rows=await env.DB.prepare("SELECT * FROM audit_log WHERE user_id=? ORDER BY created_at DESC LIMIT 200").bind(user.id).all();return json({logs:rows.results||[]})}
return json({error:"Not found"},404)}
export default{async fetch(request,env){try{return cors(await handle(request,env))}catch(error){return cors(json({error:"Server error",detail:String(error?.message||error)},500))}}};
